import { Providers } from "./providers"

export const metadata = {
  title: 'Home',
  description: 'Generated by Next.js',
}


export default function RootLayout({ children }) {
 return (
    <html lang="en">
        <body><Providers>{children}</Providers></body>
    </html>
  )
}
